[package]
name = "kvs"
version = "0.1.0"
authors = ["xxchan <xxchan@sjtu.edu.cn>"]
description = "A key-value store"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
